---
title: "regression"
author: "ruby"
date: "2018年7月30日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(dplyr)
open_data <- read.csv("./data/countries.csv", stringsAsFactors=F)
happiness <- read.csv("./data/2015.csv", stringsAsFactors=F)
colnames(open_data)[2] <- "Country"
open_data_happiness <- open_data %>%
  left_join(happiness, by = "Country") %>%
  mutate(Country = factor(Country)) %>%
  select(Country, Region, X2015.Score, Happiness.Score, Economy..GDP.per.Capita., 
         Family, Health..Life.Expectancy., Freedom, Trust..Government.Corruption., 
         Generosity, Dystopia.Residual)
colnames(open_data_happiness) <- c("Country", "Region", "Openness", "Happiness", "GDP", "Family", "Health", "Freedom", "Trust", "Generosity", "DystopiaResidual")
```
```{r}
library(formattable)
open_data_happiness %>%
  # Which countries are the most open?
  arrange(desc(Openness)) %>%
  # Round our numeric variables to two decimal places
  mutate_each(funs(round(., 2)), -c(Country, Region, Openness)) %>%
  head(10) %>%
  formattable(list(
    Openness = color_bar("yellow"),
    Happiness = color_bar("lightgreen"),
    GDP = color_bar("deepskyblue"),
    Family = color_bar("deepskyblue"),
    Health = color_bar("deepskyblue"),
    Freedom = color_bar("deepskyblue"),
    Trust = color_bar("deepskyblue"),
    Generosity = color_bar("deepskyblue"),
    DystopiaResidual = color_bar("deepskyblue")
  ), align = "l")
```
```{r cache=TRUE, warning=FALSE}
str(open_data_happiness)
head(open_data_happiness)
summary(open_data_happiness)
```
# t.test
```{r cache=TRUE, warning=FALSE}
require(ggplot2)
```
```{r cache=TRUE, warning=FALSE}
choose <- open_data_happiness %>%
  filter(Region == "Western Europe"|Region=="Southeastern Asia")
ggplot(data = choose, aes(x = Region, y = Happiness)) +
 geom_boxplot() + coord_flip() +
 labs( y = 'Happiness', x = 'Region')
```
```{r}

with(choose, 
     tapply(Happiness, Region,
     function(x) 
       c(mean(x) + c(-2, 2) * sd(x)/sqrt(length(x)))))
```
```{r}
t.test(Happiness ~ Region, data=choose)
```
# anova
```{r cache=TRUE, message=FALSE}
library(Hmisc)
```
```{r cache=TRUE, warning=FALSE}
open_data_happiness$Region <- factor(open_data_happiness$Region, 
                       levels = c('Western Europe',
                                            'North America',
                                            'Australia and New Zealand',
                                            'Middle East and Northern Africa',
                                            'Latin America and Caribbean',
                                            'Central and Eastern Europe',
                                            'Southeastern Asia',
                                            'Eastern Asia',
                                            'Sub-Saharan Africa',
                                            'Southern Asia'))


tapply(open_data_happiness$Happiness, open_data_happiness$Region, mean)

ggplot(data = open_data_happiness, 
       aes(x = Region, y = Happiness)) +
  stat_summary(fun.data = 'mean_cl_boot', size = 1) +
  scale_y_continuous(breaks = seq(500, 660, by = 20)) +
  geom_hline(yintercept = mean(open_data_happiness$Happiness) , 
             linetype = 'dotted') +
  labs(x = 'Region', y = 'Happiness') +
  coord_flip()
```
```{r cache=TRUE, warning=FALSE}
anova(m1 <- lm(Happiness ~ Region, data = open_data_happiness))
ggplot(data = open_data_happiness, 
       aes(group = Region, 
          y = Happiness, x = Health)) +
  geom_point() +
  stat_smooth(method = 'lm', se = F) +
  stat_smooth(aes(group = Region, 
          y = Happiness, x = Health), 
          method = 'lm', se = F) + 
  facet_grid( . ~  Region) +
  labs(x = 'Health', y = 'Happiness')
```
```{r cache=TRUE, warning=FALSE}
anova(m2 <- update(m1, . ~ . + 
            Health, data = open_data_happiness))
anova(m3 <- update(m2, . ~ . - Region,  data = open_data_happiness))
```
```{r cache=TRUE, warning=FALSE}
res_lm <- lapply(list(m1, m2, m3), summary)
(res_lm[[2]]$r.sq - res_lm[[3]]$r.sq)/res_lm[[2]]$r.sq
anova(m3, m2)
(res_lm[[2]]$r.sq - res_lm[[1]]$r.sq)/res_lm[[1]]$r.sq
anova(m1, m2)
```
```{r cache=TRUE, warning=FALSE}
require(coefplot)
m2 <- lm(Happiness ~ Region + Health - 1, 
         data = open_data_happiness)
coefplot(m2, xlab = '估計值', ylab = '迴歸變項', title = '反應變項 = Happiness')
```
```{r}
fit_m2 <- data.frame(open_data_happiness[, c("Region", "Health", "Happiness")], fitted = fitted(m2), resid = resid(m2),
                     infl = influence(m2)$hat )
```
```{r}
ggplot(data = fit_m2, aes(x = Happiness, group = Region )) +
 stat_density(geom = 'path', position = 'identity') +
 stat_density(geom = 'path', position = 'identity', aes(x = fitted)) +
 geom_vline(xintercept = c(with(open_data_happiness, tapply(Happiness, Region, mean))), linetype = 'dotted')+
 facet_grid(Region ~ .) +
 scale_x_continuous(breaks = seq(200, 900, by = 100))+
 labs(x = 'Happiness', y = '機率密度')
```
```{r}
ggplot(data = fit_m2, aes(x = scale(resid)), group = Region ) +
 stat_density(geom = 'path', position = 'identity', aes(linetype = Region)) +
 scale_linetype_manual(values = 10:1) +
 guides(linetype = guide_legend(reverse = TRUE)) +
 labs(x = '標準化殘差', y = '機率密度') +
 theme(legend.position = c(.15, .8))
```
# Q-Q圖
```{r}
require(lattice)
qqmath(~ scale(resid) | Region, data = fit_m2, type = c('p', 'g', 'r'),
       xlab = '常態位數', ylab = '標準化殘差', layout = c(2, 3),
       pch = '.', cex = 2)
```
```{r}
require(MASS)
ggplot(data = fit_m2, aes(x = fitted, y = scale(resid), group = Region )) +
  geom_point(pch = 20, size = 1) +
  stat_smooth(method = 'rlm', se = F) +
  facet_grid(Region ~ .) +
  labs(x = 'Happiness', y = '標準化殘差')
```
```{r}
ggplot(data = fit_m2, aes(x = infl, y = scale(resid), group = Region)) +
 geom_text(aes(label = rownames(fit_m2)), cex = 2) +
 geom_hline(yintercept = 0, linetype = 'dotted') +
 facet_grid(Region ~ .) +
 labs(x = '影響值', y = '標準化殘差')
```
```{r}
summary(influence(m2)$hat)
```